[[credentials]]
node_id = "validator-node-1"
password = "GEu6C3tb6JYNxV7zsZihepuyJlE9jhFI"
role = "validator"

[[credentials]]
node_id = "validator-node-2"
password = "p0XlKm8kh9b7NxImB13NpdRpGr67M2RE"
role = "validator"

[[credentials]]
node_id = "validator-node-3"
password = "BBZP6diM7DL6cQUTtwRc2BnUdCrF2q5b"
role = "validator"

[[credentials]]
node_id = "query-node-1"
password = "C4uXNchMFvN5BFMgzDsyIHtphQuWWBvI"
role = "query"

[[credentials]]
node_id = "query-node-2"
password = "4VeQBzF7slCzxP5brOUIyOigwIiCi3QQ"
role = "query"

[[credentials]]
node_id = "admin"
password = "TDRhdm6mTgBtRv9OOzeiB1s8Joejr9I6"
role = "admin"
