[advisories]
# Ignore unmaintained warnings for transitive dependencies we can't control
ignore = [
    # failure is unmaintained but may be used by transitive deps
    "RUSTSEC-2020-0036",
    "RUSTSEC-2019-0036",
    # paste is unmaintained but may be used by transitive deps
    "RUSTSEC-2024-0436",
]

# Warn on informational advisories but don't fail the build
informational_warnings = ["unmaintained", "unsound", "yanked"]

# Only fail on vulnerabilities with severity threshold
# Options: "none", "low", "medium", "high", "critical"
severity_threshold = "low"