node_id = "a16bee58-3dec-4ee2-b148-75766a5b6228"

[network]
listen_addresses = ["/ip4/0.0.0.0/tcp/9000"]
bootstrap_nodes = []
max_peers = 50

[consensus]
block_time_secs = 5
max_transactions_per_block = 1000

[storage]
db_path = "./data/ledger"
cache_size_mb = 128

[api]
listen_address = "127.0.0.1:8080"
enable_cors = true
max_request_size = 10485760
